parameters:
  env(MAILER_EMAIL): ''

fos_user:
  db_driver: orm
  firewall_name: main
  user_class: App\Entity\User
  from_email:
    address: '%env(resolve:MAILER_EMAIL)%'
    sender_name: '%env(resolve:MAILER_EMAIL)%'
